# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.random.rand(2)

# Create a 2-dimensional NumPy array using np.array()
two_d = np.random.rand(2,2)

# Create a 3-dimensional Numpy array using np.array()
three_d = np.random.rand(2,2,2)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(one_d)
print()
one_d.shape, one_d.ndim, type(one_d), one_d.size, one_d.dtype

[0.12716464 0.12766324]



((2,), 1, numpy.ndarray, 2, dtype('float64'))

In [5]:
# Attributes of 2-dimensional array
print(two_d)
print()
two_d.shape, two_d.ndim, type(two_d), two_d.size, two_d.dtype

[[0.01009112 0.5405441 ]
 [0.88816504 0.63940352]]



((2, 2), 2, numpy.ndarray, 4, dtype('float64'))

In [6]:
# Attributes of 3-dimensional array
print(three_d)
print()
three_d.shape, three_d.ndim, type(three_d), three_d.size, three_d.dtype

[[[0.33663343 0.48997955]
  [0.33534679 0.53118391]]

 [[0.85529088 0.23384384]
  [0.47576329 0.63541343]]]



((2, 2, 2), 3, numpy.ndarray, 8, dtype('float64'))

In [9]:
two_d

array([[0.01009112, 0.5405441 ],
       [0.88816504, 0.63940352]])

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(two_d,
                  index=["Row 1 of two_d", "Row 2 of two_d"],
                  columns=["Col 1", "Col 2"])
df

Col 1     Col 2
Row 1 of two_d  0.010091  0.540544
Row 2 of two_d  0.888165  0.639404

In [17]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
three_step = np.arange(0, 100, 3)
three_step

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_number = np.random.randint(low=0, high=11, size=(7, 2))
random_number

array([[9, 0],
       [6, 2],
       [5, 0],
       [0, 7],
       [4, 6],
       [1, 3],
       [8, 8]])

In [22]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floats = np.random.rand(3, 5)
print(random_floats)
random_floats.shape

[[0.92094769 0.24272921 0.55107001 0.16312954 0.92626146]
 [0.23891082 0.93054079 0.29101564 0.06287928 0.58444599]
 [0.11218308 0.30554463 0.95376957 0.43933215 0.05483622]]


(3, 5)

In [24]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_ints = np.random.randint(low=0, high=11, size=(4, 6))
random_ints

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(low=1, high=11, size=(3, 7))
print(random_array)
print()
# Find the unique numbers in the array you just created
np.unique(random_array)

[[10  9 10  5  2  4  7]
 [ 8  3  1  4  2  8  4]
 [ 2  6  6 10  4  6  2]]



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Find the 0'th index of the latest array you created
random_array[0]

array([10,  9, 10,  5,  2,  4,  7])

In [28]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[10,  9, 10,  5,  2,  4,  7],
       [ 8,  3,  1,  4,  2,  8,  4]])

In [29]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[10,  9],
       [ 8,  3]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_2 = np.random.randint(low=0, high=11, size=(3,5))
ones_2 = np.ones(shape=(3,5))
random_array_2, ones_2

(array([[9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [34]:
# Add the two arrays together
sum1 = random_array_2 + ones_2
sum1

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [35]:
# Create another array of ones of shape (5, 3)
ones_3 = np.ones(shape=(5, 3))
ones_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# Try add the array of ones and the other most recent array together
# ones_3 + sum1
ones_3_reshaped = ones_3.reshape(3, 5)
sum2 = ones_3_reshaped + sum1
sum2

array([[11.,  3., 11.,  5.,  9.],
       [ 8., 10.,  9.,  6.,  3.],
       [ 6.,  9., 11., 10., 10.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [39]:
# Create another array of ones of shape (3, 5)
ones_4 = np.ones(shape=(3, 5))

In [43]:
# Subtract the new array of ones from the other most recent array
diff1 = sum2 - ones_4
diff1

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [55]:
# Multiply the ones array with the latest array
mul1 = ones_4 * diff1
mul1

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [56]:
%timeit pow1 = mul1 ** 2
# Take the latest array to the power of 2 using '**'
pow1

1.18 µs ± 68.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [57]:
%timeit pow1 = np.square(mul1)
# Do the same thing with np.square()
pow1

929 ns ± 86.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


array([[100.,   4., 100.,  16.,  64.],
       [ 49.,  81.,  64.,  25.,   4.],
       [ 25.,  64., 100.,  81.,  81.]])

In [59]:
# Find the mean of the latest array using np.mean()
mean1 = np.mean(pow1)
mean1

57.2

In [61]:
# Find the maximum of the latest array using np.max()
max1 = np.max(pow1)
max1

100.0

In [63]:
# Find the minimum of the latest array using np.min()
min1 = np.min(pow1)
min1

4.0

In [64]:
# Find the standard deviation of the latest array
std1 = np.std(pow1)
std1

33.49865668948533

In [65]:
# Find the variance of the latest array
var1 = np.var(pow1)
var1

1122.16

In [86]:
# Reshape the latest array to (3, 5, 1)
pow1_reshaped = pow1.reshape((3, 5, 1))
pow1_reshaped

array([[[100.],
        [  4.],
        [100.],
        [ 16.],
        [ 64.]],

       [[ 49.],
        [ 81.],
        [ 64.],
        [ 25.],
        [  4.]],

       [[ 25.],
        [ 64.],
        [100.],
        [ 81.],
        [ 81.]]])

In [87]:
# Transpose the latest array
pow1_reshaped.T

array([[[100.,  49.,  25.],
        [  4.,  81.,  64.],
        [100.,  64., 100.],
        [ 16.,  25.,  81.],
        [ 64.,   4.,  81.]]])

What does the transpose do?

In [88]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_1 = np.random.randint(low=0, high=10, size=(3, 3))
arr_2 = np.random.randint(low=0, high=10, size=(3, 2))
arr_1, arr_2

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]]),
 array([[0, 7],
        [2, 2],
        [0, 4]]))

In [94]:
# Perform a dot product on the two newest arrays you created
print(arr_1.shape, arr_2.shape)
print()
print()
np.dot(arr_1, arr_2), np.dot(arr_2.T, arr_1)

(3, 3) (3, 2)




(array([[16, 40],
        [14, 70],
        [14, 71]]),
 array([[16, 14,  0],
        [44, 98, 50]]))

In [95]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_3 = np.random.randint(low=0, high=10, size=(4, 3))
arr_4 = np.random.randint(low=0, high=10, size=(4, 3))
arr_3, arr_4

(array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0],
        [6, 6, 7]]),
 array([[4, 2, 7],
        [5, 2, 0],
        [2, 4, 2],
        [0, 4, 9]]))

In [96]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_3, arr_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [98]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr_3.T, arr_4) , np.dot(arr_3, arr_4.T)

(array([[ 90,  86, 131],
        [ 56,  52,  98],
        [ 76,  62, 126]]),
 array([[111,  57,  60, 105],
        [100,  52,  56,  96],
        [ 30,  37,  18,   4],
        [ 85,  42,  50,  87]]))

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [100]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
shape= (3,3)
a1 = np.random.randint(low=0, high=10, size=shape)
a2 = np.random.randint(low=0, high=10, size=shape)
a1, a2

(array([[9, 8, 4],
        [5, 3, 9],
        [6, 8, 6]]),
 array([[0, 0, 8],
        [8, 3, 8],
        [2, 6, 5]]))

In [101]:
# Compare the two arrays with '>'
a1 > a2

array([[ True,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [102]:
# Compare the two arrays with '>='
a1 >= a2

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [103]:
# Find which elements of the first array are greater than 7
a1 > 7

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False]])

In [104]:
# Which parts of each array are equal? (try using '==')
a1 == a2

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [109]:
# Sort one of the arrays you just created in ascending order
print(a1)
print()
print(np.sort(a1, axis=-1)) # -1 is last axis which are elements
print()
print(np.sort(a1, axis=0))
print()
print(np.sort(a1, axis= None))

[[9 8 4]
 [5 3 9]
 [6 8 6]]

[[4 8 9]
 [3 5 9]
 [6 6 8]]

[[5 3 4]
 [6 8 6]
 [9 8 9]]

[3 4 5 6 6 8 8 9 9]


In [120]:
# Sort the indexes of one of the arrays you just created
print(a1)
print()
np.argsort(a1)

[[9 8 4]
 [5 3 9]
 [6 8 6]]



array([[2, 1, 0],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [134]:
# Find the index with the maximum value in one of the arrays you've created
print(arr_4)
print()
print(np.argmax(arr_4))
print(np.argmax(arr_4, keepdims=True))
print()
# to find max value using argmax index
arr_4[np.unravel_index(11, arr_4.shape)]

[[4 2 7]
 [5 2 0]
 [2 4 2]
 [0 4 9]]

11
[[11]]



9

In [137]:
# Find the index with the minimum value in one of the arrays you've created
print(arr_4)
print()
print(np.argmin(arr_4))
print()
print(np.unravel_index(np.argmin(arr_4), arr_4.shape))
print()
print(arr_4[np.unravel_index(np.argmin(arr_4), arr_4.shape)])

[[4 2 7]
 [5 2 0]
 [2 4 2]
 [0 4 9]]

5

(1, 2)

0


In [142]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(arr_4)
print()
max_indx = np.argmax(arr_4, axis=1)
print(max_indx)
print()
print([arr_4[row][indx] for row, indx in enumerate(max_indx)])

[[4 2 7]
 [5 2 0]
 [2 4 2]
 [0 4 9]]

[2 0 1 2]

[7, 5, 4, 9]


In [145]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(arr_4)
print()
min_indx = np.argmin(arr_4, axis=0)
print(min_indx)
print()
print([arr_4[indx][col] for col, indx in enumerate(min_indx)])

[[4 2 7]
 [5 2 0]
 [2 4 2]
 [0 4 9]]

[3 0 1]

[0, 2, 0]


In [179]:
# Create an array of normally distributed random numbers
normal_dis_arr = np.random.normal(loc=5.0, scale=2.0, size=(1,10))
normal_dis_arr

array([[4.02657101, 7.66889128, 6.96309475, 5.66140111, 4.97056348,
        6.59281086, 4.43722979, 1.67061361, 4.98760172, 5.80623865]])

In [182]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.